export enum ErrorCode {
  DATABASE_SEARCH_ERROR = 1,
  EMAIL_ALREADY_EXISTS,
  USERNAME_ALREADY_EXISTS,
  USERNAME_OR_EMAIL_DOES_NOT_EXIST,
  USER_NOT_FOUND,
  INCORRECT_PASSWORD,
  EMAIL_SENDING_ERROR,
  INVALID_ERROR_CONFIRMATION_CODE,
  SESSION_NOT_FOUND,
  NO_ACCESS_TOKEN_PROVIDED,
}
