"use strict";var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.owns=function(b,c){return Object.prototype.hasOwnProperty.call(b,c)};$jscomp.assign="function"==typeof Object.assign?Object.assign:function(b,c){for(var d=1;d<arguments.length;d++){var e=arguments[d];if(e)for(var f in e)$jscomp.owns(e,f)&&(b[f]=e[f])}return b};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,c,d,e){if(c){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in d||(d[f]={});d=d[f]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Object.assign",function(b){return b||$jscomp.assign},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var b=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+b++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(b){var c=0;return $jscomp.iteratorPrototype(function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}})};$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};
$jscomp.iteratorFromArray=function(b,c){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var d=0,e={next:function(){if(d<b.length){var f=d++;return{value:c(f,b[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.from",function(b){return b?b:function(b,d,e){$jscomp.initSymbolIterator();d=null!=d?d:function(a){return a};var f=[],c=b[Symbol.iterator];if("function"==typeof c){b=c.call(b);for(var a=0;!(c=b.next()).done;)f.push(d.call(e,c.value,a++))}else for(c=b.length,a=0;a<c;a++)f.push(d.call(e,b[a],a));return f}},"es6","es3");
var $$=function(){function b(a,b){if(!a){b=b||"Assertion failed";if("undefined"!==typeof Error)throw Error(b);throw b;}}function c(a,b){a=Array.from((b||document).querySelectorAll(a)).map(function(a){return f.expand(a,h,!0)});return 1===a.length?a[0]:d(a)}function d(a){Object.getOwnPropertyNames(h).forEach(function(b){if("function"===typeof h[b]&&!a.hasOwnProperty(b)){var g={};g[b]=function(){var g=Array.from(arguments),c=[];a.forEach(function(a){c.push(a[b].apply(a,g))});return d(Array.prototype.concat.apply([],
c))};f.expand(a,g)}});return a}function e(a){if(a instanceof HTMLElement)return f.expand(a,h,!0),a;if("string"===typeof a)return c(a);throw Error("Given argument type is incopatible ("+typeof a+")");}"undefined"===typeof Array.isArray&&(Array.isArray=function(a){return"[object Array]"===Object.prototype.toString.call(a)});window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||
function(a){window.setTimeout(a,1E3/60)}}();var f={assert:b,expand:function(a,b,c){void 0===c&&(c=!1);if(!c)return Object.assign(a,b);Object.getOwnPropertyNames(b).forEach(function(g){a[g]=b[g]});return a},load:function(a){document.body?"function"===typeof a&&a():document.onload=window.onload=a},loadFile:function(a,b){try{var c=new XMLHttpRequest;c.open("GET",a,!0);c.onreadystatechange=function(){"function"===typeof b&&4==c.readyState&&b(200==c.status?c.responseText:void 0)};c.send()}catch(l){console.error("Cannot load file:",
l),"function"===typeof b&&b()}},postRequest:function(a,b,c){try{"string"!==typeof b&&(b=Object.keys(b).map(function(a){return a+"\x3d"+b[a]}).join("\x26"));var g=new XMLHttpRequest;g.open("POST",a,!0);g.onreadystatechange=function(){"function"===typeof c&&4==g.readyState&&c(200==g.status?g.responseText:void 0)};g.setRequestHeader("Content-type","application/x-www-form-urlencoded");g.send(b)}catch(m){console.error("Post request error:",m),"function"===typeof c&&c(void 0)}},loadScript:function(a,g,
d){b(!!document.head,"Document head not found");var e=f.create("SCRIPT");e.setAttribute("type","text/javascript");e.setAttribute("src",a);e.setAttribute("async",String(!!g));c("SCRIPT").some(function(b){return-1!=b.src.indexOf(a)})?"function"===typeof d&&d():("function"===typeof d&&(e.onload=d),document.head.appendChild(e))},try:function(a,b){try{a.apply(a,Array.from(arguments).slice(2,arguments.length))}catch(k){console.error(b||"error: ",k)}},runAsync:function(a,b){void 0===b&&(b=1);setTimeout(a,
b)},create:function(a){a=document.createElement(a.replace(/[^(a-zA-Z0-9)]*/gi,""));return f.expand(a,h)},getScreenSize:function(){return{width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight}},base64encode:function(a){return window.btoa(a)},base64decode:function(a){return window.atob(a)}},h={html:function(a){this.innerHTML=String(a);return this},setText:function(a){this.innerText=
String(a);return this},addText:function(a){this.appendChild(document.createTextNode(String(a)));return this},addClass:function(a){this.classList.add(a);return this},removeClass:function(a){this.classList.remove(a);return this},setClass:function(a){this.className=a;return this},getChildren:function(a){return c(a,this)},addChild:function(a){if(Array.isArray(a)){for(var b=0;b<a.length;b++)this.append(a[b]);return this}this.appendChild(a);return this},appendAtBeginning:function(a){if(Array.isArray(a)){for(var b=
0;b<a.length;b++)this.appendAtBeginning(a[b]);return this}this.insertBefore(a,this.firstChild);return this},delete:function(){this.remove()},setStyle:function(a){f.expand(this.style,a,!0);return this},setAttrib:function(a,b){this.setAttribute(a,String(b));return this},getAttrib:function(a){return this.getAttribute(a)},getPos:function(){var a=this.getBoundingClientRect();return{x:a.left,y:a.top}},getWidth:function(){var a=this.getBoundingClientRect();return a.right-a.left},getHeight:function(){var a=
this.getBoundingClientRect();return a.bottom-a.top},on:function(a,b){if(this.addEventListener)this.addEventListener(a,b,!1);else throw Error("no addEventListener support");return this},off:function(a,b){if(this.removeEventListener)this.removeEventListener(a,b,!1);else throw Error("no removeEventListener support");return this}};f.expand(e,f);return e}();window.$$=$$;